{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dnsweaver.fullname" . }}
  labels:
    {{- include "dnsweaver.labels" . | nindent 4 }}
rules:
  {{- if .Values.rbac.watchIngress }}
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  {{- end }}
  {{- if .Values.rbac.watchIngressRoute }}
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch"]
  {{- end }}
  {{- if .Values.rbac.watchHTTPRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["get", "list", "watch"]
  {{- end }}
  {{- if .Values.rbac.watchServices }}
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  {{- end }}
{{- end }}
